In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu121


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int using item()
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9]],[[3,2,1],[4,5,6]],[[3,2,1],[4,5,6]],[[3,2,1],[4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9]],

        [[3, 2, 1],
         [4, 5, 6]],

        [[3, 2, 1],
         [4, 5, 6]],

        [[3, 2, 1],
         [4, 5, 6]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([4, 2, 3])

In [16]:
TENSOR[2]

tensor([[3, 2, 1],
        [4, 5, 6]])

### Random tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4935, 0.4547, 0.9544, 0.2591],
        [0.8612, 0.8835, 0.9102, 0.5084],
        [0.3275, 0.4599, 0.8418, 0.9335]])

In [18]:
random_tensor.ndim

2

In [19]:
# Creat a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (224,224,3)) # height , width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

ten_ones = torch.ones_like(input=one_to_ten)
print(ten_ones)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [26]:
# FLoat 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on (cuda, cpu)
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [27]:
# Change tensor dtype
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [28]:
float_32_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [29]:
# int 32 tensor
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

#### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [30]:
# Create a tensor

some_tensor = torch.rand([3, 4])
some_tensor

tensor([[0.9451, 0.8898, 0.4957, 0.2813],
        [0.0221, 0.7481, 0.2322, 0.0970],
        [0.0269, 0.2188, 0.6444, 0.2203]])

In [32]:
# Findout the details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9451, 0.8898, 0.4957, 0.2813],
        [0.0221, 0.7481, 0.2322, 0.0970],
        [0.0269, 0.2188, 0.6444, 0.2203]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplicaion in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication

In [39]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
tensor

tensor([1, 2, 3])

In [42]:
# Maatrix multication by hand
1*1 + 2*2 + 3*3

14

In [43]:
%%time
value = 0
for i in range(len(tensor)):
     value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.93 ms, sys: 0 ns, total: 2.93 ms
Wall time: 3.06 ms


In [44]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 512 µs, sys: 33 µs, total: 545 µs
Wall time: 433 µs


tensor(14)